# Generated by Django 4.2.1 on 2023-05-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='coutry',
            new_name='country',
        ),
    ]
